import { test, expect } from '@playwright/test';
import { DEMO } from '../../contracts/demo';
test('backend catalog, pinned lesson, fresh-device recovery and outage-safe local progress', async ({ page, browser }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Start Teaching' }).click();
  await expect(page.getByText('Catalog from the school API')).toBeVisible();
  await page.getByRole('button', { name: /Demo class/ }).click();
  await page.getByRole('button', { name: /Visual exploration/ }).click();
  await page.getByRole('button', { name: /Observe and describe/ }).click();
  await page.getByRole('button', { name: 'Start Teaching' }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Square', exact: true }).click();
  await page.getByRole('button', { name: 'Annotate', exact: true }).click();
  const surface = page.getByRole('region', { name: 'Content annotation surface' });
  const box = await surface.boundingBox(); if (!box) throw new Error('Missing surface');
  await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
  await expect(page.getByRole('status')).toHaveText('Lesson and ink synced', { timeout: 20000 });
  const url = page.url(); const id = new URL(url).searchParams.get('session');
  const remote = await (await page.request.get(`/api/v1/sessions/${id}`)).json();
  expect(remote.lessonVersionId).toBe(DEMO.version); expect(remote.documents).toHaveLength(4);
  const fresh = await browser.newContext(); const recovered = await fresh.newPage(); await recovered.goto(url);
  await expect(recovered.getByRole('button', { name: 'Activity outline' })).toContainText('2 of 3');
  await expect(recovered.getByRole('button', { name: 'Square', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(recovered.getByRole('region', { name: 'Content annotation surface' })).toHaveAttribute('data-ink-count', '1');
  await fresh.close();
  await page.route('**/api/v1/**', route => route.abort('connectionrefused'));
  await page.getByRole('button', { name: 'Next', exact: true }).click(); await page.getByRole('button', { name: 'Reveal next' }).click();
  await expect(page.getByRole('status')).toHaveText('Saved on this device · Server unavailable');
  await page.reload(); await expect(page.getByText('1 of 3 prompts revealed')).toBeVisible();
  await page.getByRole('button', { name: 'Reveal next' }).click();
  await expect(page.getByText('2 of 3 prompts revealed')).toBeVisible();
  await page.unroute('**/api/v1/**');
  await expect(page.getByRole('status')).toHaveText('Lesson and ink synced', { timeout: 20000 });
  const latest = await (await page.request.get(`/api/v1/sessions/${id}`)).json();
  expect(latest.progress.states[latest.progress.currentActivityId].revealed).toBe(2);
});
